### ISSUE TITLE
Data Structure needed for training the algorithm

### ISSUE THREAD

**Issue by muammar** [aaayushg/generative_IDPs#2]
The algorithm needs PDB files to run; would it be possible to create an `example` directory with a small toy dataset to make it easier for users to apply the algorithm?

Thanks.

**Comment by muammar** [comment]
This is just a follow-up to my previous message. Would you have some toy datasets that I could use to try your implementation?

**Comment by aaayushg** [comment]
Hello, I just uploaded polyq_1000frames.pdb in the implementation_codes folder. You can use it as a test trajectory - It has a total of 1000 frames so please change the test and training size accordingly.
Apologies for the very late reply. Let me know if you have any other questions.

**Comment by muammar** [comment]
@aaayushg, no worries, and thanks for your reply. I will play with your implementation, and I will let you know if something comes up.

**Comment by muammar** [comment]
I opened https://github.com/aaayushg/generative_IDPs/pull/3 to fix some issues to make the code work. I am dealing with this error:

```
Traceback (most recent call last):
  File "/home/muammar/dgx1/Research/19_MDML/generative_IDPs/Implementation_codes/./autoencoder_train_generate.py", line 183, in <module>
    test_structs = M.get_subset(idxs=idx, conformations=indicestest)
  File "/home/muammar/miniconda3/envs/generative_ipds/lib/python3.9/site-packages/biobox/classes/molecule.py", line 1212, in get_subset
    raise Exception("ERROR: requested coordinate index %s, but only %s are available" %(np.max(conformations), len(self.coordinates)))
Exception: ERROR: requested coordinate index 94999, but only 1000 are available
(generative_ipds)
```

It looks like those indices are hard coded somewhere. Would you know how I could quickly fix this? I will try to make it work myself in the interim. 

Best,

**Comment by aaayushg** [comment]
Hi Muammar, 
Thanks for your pull request - I will try to look into it.
Quick fix for your particular case - you will need to change lines 179 and 182 in `autoencoder_train_generate.py`
```
indicestrain = np.arange(0,19000,1)
indicestest = np.arange(19000,95000,1)
```

**Comment by muammar** [comment]
> Hi Muammar, Thanks for your pull request - I will try to look into it. Quick fix for your particular case - you will need to change lines 179 and 182 in `autoencoder_train_generate.py`
> 
> ```
> indicestrain = np.arange(0,19000,1)
> indicestest = np.arange(19000,95000,1)
> ```

Thank you. I changed based on the logic above to this: 

```

diff --git a/Implementation_codes/autoencoder_train_generate.py b/Implementation_codes/autoencoder_train_generate.py
index cf44071..ffe374e 100644
--- a/Implementation_codes/autoencoder_train_generate.py
+++ b/Implementation_codes/autoencoder_train_generate.py
@@ -176,10 +176,10 @@ print("> selected %s atoms"%len(idx))
 #randomly separate simulation in training and test set
 print("> extracting %s random items for test set"% test_size)
 #indices = np.random.permutation(len(crds))
-indicestrain = np.arange(0,19000,1)
+indicestrain = np.arange(0,800,1)
 
 # save structures of test set for later comparison
-indicestest = np.arange(19000,95000,1)
+indicestest = np.arange(800,1000,1)
 test_structs = M.get_subset(idxs=idx, conformations=indicestest)
 test_structs.write_pdb("%s/%s_test_set.pdb"%(outfolder, outlabel))
 train_structs = M.get_subset(idxs=idx, conformations=indicestrain)
```

That creates the following issue:

```
Traceback (most recent call last):
  File "/home/muammar/dgx1/Research/19_MDML/generative_IDPs/Implementation_codes/./autoencoder_train_generate.py", line 184, in <module>
    test_structs.write_pdb("%s/%s_test_set.pdb"%(outfolder, outlabel))
  File "/home/muammar/miniconda3/envs/generative_ipds/lib/python3.9/site-packages/biobox/classes/molecule.py", line 1358, in write_pdb
    no, split, _ = self.guess_chain_split()
  File "/home/muammar/miniconda3/envs/generative_ipds/lib/python3.9/site-packages/biobox/classes/molecule.py", line 1264, in guess_chain_split
    raise Exception("mismatch in N and C count")
Exception: mismatch in N and C count
```

**Comment by aaayushg** [comment]
Apologies for months late reply. Is it still an issue? Maybe because of atom types - code truncates the full protein into heavy atoms of specific type.

**Comment by muammar** [comment]
This is still an issue, and I could not make it work. Would you know how to fix it?

**Comment by aaayushg** [comment]
Super late here. but were you able to solve it?

**Comment by muammar** [comment]
No, I could not use this algorithm.
